version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `requirements.txt` and `pyproject.toml` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Create pull requests for version updates
    open-pull-requests-limit: 10
    # Apply labels to pull requests
    labels:
      - "dependencies"
      - "automated"
    # Group updates by dependency name and update type
    versioning-strategy: "increase"
    # Automatically rebase the PR if it becomes outdated
    rebase-strategy: "auto"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "github-actions"
      - "dependencies"
      - "automated"
